---
abstract: 'AnyEvent HTTP/2 (draft 12) Server for PSGI'
author:
  - 'Vladimir Lettiev <thecrux@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Minilla/v1.0.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shuvgey
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Handler::Shuvgey:
    file: lib/Plack/Handler/Shuvgey.pm
  Shuvgey:
    file: lib/Shuvgey.pm
    version: 0.02
  Shuvgey::Server:
    file: lib/Shuvgey/Server.pm
requires:
  AnyEvent: 0
  Net::SSLeay: '> 1.45'
  Plack: 0
  Protocol::HTTP2: 0.06
  URI::Escape: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/vlet/Shuvgey/issues
  homepage: https://github.com/vlet/Shuvgey
  repository: git://github.com/vlet/Shuvgey.git
version: 0.02
x_authority: cpan:CRUX
