---
abstract: 'AnyEvent HTTP/2 (draft 14) Server for PSGI'
author:
  - 'Vladimir Lettiev <thecrux@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Shuvgey
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Handler::Shuvgey:
    file: lib/Plack/Handler/Shuvgey.pm
  Shuvgey:
    file: lib/Shuvgey.pm
    version: '0.04'
  Shuvgey::Server:
    file: lib/Shuvgey/Server.pm
requires:
  AnyEvent: '0'
  Net::SSLeay: '1.56'
  Plack: '0'
  Protocol::HTTP2: '0.11'
  Sys::Hostname: '0'
  URI::Escape: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/vlet/Shuvgey/issues
  homepage: https://github.com/vlet/Shuvgey
  repository: git://github.com/vlet/Shuvgey.git
version: '0.04'
x_authority: cpan:CRUX
